stages:
  - springboot_build
  - springboot_deploy

springboot_build-job:
  stage: springboot_build
  script:
    - cd Backend
    - mvn clean package
  tags:
    - springboot_tag
  only:
    - main

springboot_deploy-job:
  stage: springboot_deploy
  script:
    - cd Backend
    - mvn package
    - sudo cp target/*.jar /target/server.jar
    - sudo chmod +x /target/server.jar
    - sudo systemctl restart deploy.service
  tags:
    - springboot_tag
  only:
    - main

