stages:
  - springboot_build
  - springboot_deploy

springboot_build-job:
  stage: springboot_build
  script:
    - cd VetGo
    - mvn clean package
  tags:
    - springboot_tag
  only:
    - main

springboot_deploy-job:
  stage: springboot_deploy
  script:
    - cd VetGo
    - mvn package
    - sudo systemctl restart system-deploy
  tags:
    - springboot_tag
  only:
    - main

