# Generated by Django 5.0.2 on 2024-02-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetgouser',
            name='role',
            field=models.CharField(choices=[('vet_doc', 'Veterinary Doctor'), ('pet_owner', 'Pet Owner')], default='pet_owner', max_length=9),
        ),
    ]
